# Run update.sh in each submodule folder
name: Update AUR packages

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
  push:
  pull_request:

env:
  AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}

jobs:
  checkout-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.check.outputs.packages }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Check
      run: |
        packages=$(find . -mindepth 1 -maxdepth 1 -type d -exec test -e '{}/PKGBUILD' \; -print | sed 's|^\./||')
        echo "::set-output name=packages::${packages}"
  update:
    runs-on: ubuntu-latest
    needs: checkout-packages
    strategy:
      matrix:
        packages: ${{fromJson(needs.checkout-packages.outputs.packages)}}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Update
      run: |
        for package in ${{ matrix.packages }}; do
          cd $package
          ./update.sh
          cd ..
        done
